services:
  feed-crafter:
    build: .
    container_name: feed-crafter
    network_mode: bridge
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=3000
      - CHANNEL_TITLE="RSS Channel"
      - CHANNEL_LINK=http://localhost:3000
      - CHANNEL_DESCRIPTION="An RSS feed."
    volumes:
      - ./feed:/app/feed
    ports:
      - 3000:3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5